version: "2"

services:

  mongo:
    image: sammlerio/mongo:latest@sha256:c8a1941d19da89eaa84b30276ec350e54f2e80bcd3bdd81f69a8f13070e8b333
    ports:
      - "27017:27017"

  api:
    build:
      context: ./services/api
    depends_on:
      - mongo
    environment:
      - NODE_ENV=dev
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    volumes:
      - "./services/api:/home/app"
    command: ["npm", "run", "start:dev"]

