version: "2"

services:

  # --------------------------------------
  #              Infrastructure
  # --------------------------------------
  mongo:
    image: sammlerio/mongo
    container_name: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none

  nats-streaming:
    image: nats-streaming
    container_name: nats-streaming
    ports:
      - "4222:4222"
      - "4223:4223"
      - "8223:8223"
      - "8222:8222"
    volumes:
      - ./.datastore:/datastore
    command: [
      "-m", "8222",
      "--store", "FILE",
      "--dir", "datastore"
    ]
    logging:
      driver: none

  # --------------------------------------
  #              Services
  # --------------------------------------
  jobs-service:
    image: sammlerio/jobs-service
    container_name: jobs-service
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3003
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=db
      - NATS_STREAMING_HOST=nats-streaming
      - NATS_STREAMING_PORT=4222
      - ENABLE_AUDIT_LOG=true
    ports:
      - "3003:3003"
    volumes:
      - "./:/opt/jobs-service"
    depends_on:
      - mongo
      - nats-streaming
    command: ["npm", "run", "start:watch"]

  auth-service:
    image: sammlerio/auth-service
    container_name: auth-service
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=db
      - NATS_STREAMING_HOST=nats-streaming
      - NATS_STREAMING_PORT=4222
      - ENABLE_AUDIT_LOG=true
    depends_on:
      - mongo
      - nats-streaming

